---
name: 'Tests Action'
description: 'Call Tests and get the results'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true

    - name: Run Go Tests
      run: go test -run TestAzure
      working-directory: $GITHUB_ACTION_REPOSITORY/tests/terratest
