---
name: 'Tests Action'
description: 'Call Tests and get the results'
inputs:
  tool:
    description: 'name of the test tool to use e.g. terratest'
    required: true
    default: terrascan
  testname:
    description: 'name of the test to run e.g. TestAzure'
    required: true
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tool}}
    - ${{ inputs.testname}}
