---
name: 'Tests Action'
description: 'Call Tests and get the results'
inputs:
  work_dir:
    description: 'name of the directory where the action is located'
    required: true
    default: '.github/actions/trial'
  tool:
    description: 'name of the tool to use e.g. terratest'
    required: true
  test:
    description: 'name of the test to run e.g. azure'
    required: true
  debug:
    description: 'should debug mode be enabled'
    required: false
    default: 'false'
outputs: {}
runs:
  using: 'composite'
  steps:
    - run: echo ${{ inputs.work_dir }} ${{ inputs.tool }} ${{ inputs.test }}
    - run: ls -la .*
    - run: if [ "${{ inputs.debug }}" == "true" ]; then debug_mode="-v"; else debug_mode=""; fi  && cd ${{ inputs.work_dir }} && go test $debug_mode ${{ inputs.tool }}/${{ inputs.test }}_test.go
