---
name: 'Tests Action'
description: 'Call Tests and get the results'
inputs:
  work_dir:
    description: 'name of the directory where the action is located (./test-action)'
    required: true
    default: './test-action'
  tool:
    description: 'name of the tool to use (terratest)'
    required: true
    default: 'terratest'
  test:
    description: 'name of the test to run (azure)'
    required: true
  debug:
    description: 'should debug mode be enabled (true, false)'
    required: false
    default: 'false'
outputs: {}
runs:
  using: 'composite'
  steps:
    - run: |
        if [ \"${{ inputs.debug }}\" == \"true\" ]; then debug_mode='-v'; else debug_mode=''; fi && cd ${{ inputs.work_dir }}/tests && go test $debug_mode ${{ inputs.tool }}/${{ inputs.test }}_test.go
